### ISSUE TITLE
First draft issues

### ISSUE THREAD

**Issue by tomhamiltonstubber** [tutorcruncher/tutorcruncher.github.io#1]
* [x] Pricing and features should be swapped in the menu to match the order they are on the page.
* [x] Favicon needed
* [x] Tutoring Directory needs brought in
* [x] Blog needed
* [x] Video needs changed. Or keep the current one, its cool too.
* [x] The content under features needs looking at, spag mistakes.
* [x] The text before Sign Up for Free is wrong.
* [x] Team section needs filling
* [x] Contact Us needs doing
* [x] Footer needs doing
* [x] Thematic break needed for Pricing header
* [x] Perhaps we should change the pricing table? The text looks a bit small
* [x] TutorCruncher in the menu should have our icon
* [x] Should we be showing the icon more do you think?

**Comment by samuelcolvin** [comment]
@tomhamiltonstubber can you fix:

> The content under features needs looking at, spag mistakes.
> The text before Sign Up for Free is wrong.
